from __future__ import annotations


TEMPLATES = [
    {
        "id": "small-company",
        "name": "Small Company",
        "description": "A compact enterprise network with frontend, auth, employee, admin, and database services.",
        "services": [
            {"name": "frontend-service", "type": "frontend", "port": 8080, "exposed": True, "vulnerabilities": []},
            {"name": "auth-service", "type": "api", "port": 8081, "exposed": False, "vulnerabilities": ["weak_login_rate_limit"]},
            {"name": "employee-api", "type": "api", "port": 8082, "exposed": False, "vulnerabilities": ["demo_search_input"]},
            {"name": "admin-api", "type": "api", "port": 8083, "exposed": False, "vulnerabilities": ["restricted_endpoint_demo"]},
            {"name": "postgres-db", "type": "database", "port": 5432, "exposed": False, "vulnerabilities": []},
            {"name": "traffic-generator", "type": "worker", "port": None, "exposed": False, "vulnerabilities": []},
        ],
        "normal_traffic": ["GET /home", "POST /login", "GET /profile", "GET /employees", "GET /search?q=alice"],
    },
    {
        "id": "e-commerce",
        "name": "E-Commerce",
        "description": "A storefront template with products, cart, payment, orders, cache, and database components.",
        "services": [
            {"name": "frontend-service", "type": "frontend", "port": 8080, "exposed": True, "vulnerabilities": []},
            {"name": "auth-service", "type": "api", "port": 8081, "exposed": False, "vulnerabilities": ["weak_login_rate_limit"]},
            {"name": "product-service", "type": "api", "port": 8082, "exposed": False, "vulnerabilities": ["demo_search_input"]},
            {"name": "cart-service", "type": "api", "port": 8083, "exposed": False, "vulnerabilities": []},
            {"name": "payment-service", "type": "api", "port": 8084, "exposed": False, "vulnerabilities": ["restricted_endpoint_demo"]},
            {"name": "order-service", "type": "api", "port": 8085, "exposed": False, "vulnerabilities": []},
            {"name": "postgres-db", "type": "database", "port": 5432, "exposed": False, "vulnerabilities": []},
            {"name": "redis-cache", "type": "cache", "port": 6379, "exposed": False, "vulnerabilities": []},
            {"name": "traffic-generator", "type": "worker", "port": None, "exposed": False, "vulnerabilities": []},
        ],
        "normal_traffic": ["GET /home", "POST /login", "GET /products", "POST /cart/add", "GET /orders"],
    },
    {
        "id": "university",
        "name": "University",
        "description": "A campus system with student portal, auth, marks, fees, admin, and database services.",
        "services": [
            {"name": "student-portal", "type": "frontend", "port": 8080, "exposed": True, "vulnerabilities": []},
            {"name": "auth-service", "type": "api", "port": 8081, "exposed": False, "vulnerabilities": ["weak_login_rate_limit"]},
            {"name": "marks-api", "type": "api", "port": 8082, "exposed": False, "vulnerabilities": ["demo_search_input"]},
            {"name": "fees-api", "type": "api", "port": 8083, "exposed": False, "vulnerabilities": []},
            {"name": "admin-api", "type": "api", "port": 8084, "exposed": False, "vulnerabilities": ["restricted_endpoint_demo"]},
            {"name": "postgres-db", "type": "database", "port": 5432, "exposed": False, "vulnerabilities": []},
            {"name": "traffic-generator", "type": "worker", "port": None, "exposed": False, "vulnerabilities": []},
        ],
        "normal_traffic": ["GET /portal", "POST /login", "GET /marks", "GET /fees", "GET /profile"],
    },
]


SCENARIOS = [
    {
        "id": "brute-force-login",
        "scenario_name": "Brute Force Login Simulation",
        "description": "Repeated failed login attempts using fake credentials against the lab auth service.",
        "difficulty": "Beginner",
        "attack_type": "Brute Force",
        "allowed_template_ids": ["small-company", "e-commerce", "university"],
        "target_services": ["auth-service"],
        "default_risk": "High",
        "steps": [
            {
                "order": 1,
                "action_type": "HTTP_REQUEST_PATTERN",
                "source": "attack-pod",
                "target": "auth-service",
                "method": "POST",
                "endpoint": "/login",
                "event_type": "failed_login",
                "payload_category": "credential_attempt",
                "status_code": 401,
                "count": 34,
            }
        ],
    },
    {
        "id": "sql-injection",
        "scenario_name": "SQL Injection Simulation",
        "description": "Predefined suspicious input patterns sent to a vulnerable demo search endpoint.",
        "difficulty": "Intermediate",
        "attack_type": "SQL Injection",
        "allowed_template_ids": ["small-company", "e-commerce", "university"],
        "target_services": ["employee-api", "product-service", "marks-api"],
        "default_risk": "High",
        "steps": [
            {
                "order": 1,
                "action_type": "HTTP_REQUEST_PATTERN",
                "source": "attack-pod",
                "target": "employee-api",
                "method": "GET",
                "endpoint": "/search",
                "event_type": "suspicious_input_pattern",
                "payload_category": "sql_meta_characters",
                "status_code": 200,
                "count": 18,
            }
        ],
    },
    {
        "id": "privilege-escalation",
        "scenario_name": "Privilege Escalation Attempt",
        "description": "A fake low-privilege user attempts restricted admin operations.",
        "difficulty": "Intermediate",
        "attack_type": "Privilege Escalation",
        "allowed_template_ids": ["small-company", "e-commerce", "university"],
        "target_services": ["admin-api", "payment-service"],
        "default_risk": "High",
        "steps": [
            {
                "order": 1,
                "action_type": "UNAUTHORIZED_ACCESS_ATTEMPT",
                "source": "attack-pod",
                "target": "admin-api",
                "method": "GET",
                "endpoint": "/admin/users",
                "event_type": "restricted_endpoint_access",
                "payload_category": "low_privilege_token",
                "status_code": 403,
                "count": 12,
            }
        ],
    },
    {
        "id": "lateral-movement",
        "scenario_name": "Lateral Movement Simulation",
        "description": "A simulated attacker moves across internal services toward admin and database components.",
        "difficulty": "Advanced",
        "attack_type": "Lateral Movement",
        "allowed_template_ids": ["small-company", "university"],
        "target_services": ["frontend-service", "auth-service", "employee-api", "admin-api", "postgres-db"],
        "default_risk": "Critical",
        "steps": [
            {
                "order": 1,
                "action_type": "HTTP_REQUEST_PATTERN",
                "source": "attack-pod",
                "target": "frontend-service",
                "method": "GET",
                "endpoint": "/home",
                "event_type": "initial_probe",
                "payload_category": "service_probe",
                "status_code": 200,
                "count": 8,
            },
            {
                "order": 2,
                "action_type": "AUTHENTICATION_SEQUENCE",
                "source": "frontend-service",
                "target": "auth-service",
                "method": "POST",
                "endpoint": "/login",
                "event_type": "credential_reuse_attempt",
                "payload_category": "credential_attempt",
                "status_code": 401,
                "count": 10,
            },
            {
                "order": 3,
                "action_type": "INTERNAL_API_ACCESS",
                "source": "auth-service",
                "target": "employee-api",
                "method": "GET",
                "endpoint": "/employees",
                "event_type": "internal_service_hop",
                "payload_category": "service_discovery",
                "status_code": 200,
                "count": 7,
            },
            {
                "order": 4,
                "action_type": "UNAUTHORIZED_ACCESS_ATTEMPT",
                "source": "employee-api",
                "target": "admin-api",
                "method": "GET",
                "endpoint": "/admin/users",
                "event_type": "restricted_endpoint_access",
                "payload_category": "low_privilege_token",
                "status_code": 403,
                "count": 6,
            },
            {
                "order": 5,
                "action_type": "DATABASE_ACCESS_ATTEMPT",
                "source": "admin-api",
                "target": "postgres-db",
                "method": "CONNECT",
                "endpoint": "tcp/5432",
                "event_type": "database_reachability_attempt",
                "payload_category": "db_probe",
                "status_code": 0,
                "count": 4,
            },
        ],
    },
    {
        "id": "multi-stage-chain",
        "scenario_name": "SQL Injection to Lateral Movement",
        "description": "SQL injection signal, fake credential exposure, admin access attempt, and database reachability attempt.",
        "difficulty": "Advanced",
        "attack_type": "Multi-Stage Attack",
        "allowed_template_ids": ["small-company", "university"],
        "target_services": ["employee-api", "admin-api", "postgres-db"],
        "default_risk": "Critical",
        "steps": [
            {
                "order": 1,
                "action_type": "HTTP_REQUEST_PATTERN",
                "source": "attack-pod",
                "target": "employee-api",
                "method": "GET",
                "endpoint": "/search",
                "event_type": "suspicious_input_pattern",
                "payload_category": "sql_meta_characters",
                "status_code": 200,
                "count": 16,
            },
            {
                "order": 2,
                "action_type": "SIMULATED_CREDENTIAL_DISCOVERY",
                "source": "employee-api",
                "target": "admin-api",
                "method": "SIMULATE",
                "endpoint": "/artifact/fake-credential",
                "event_type": "credential_artifact_generated",
                "payload_category": "credential_artifact",
                "status_code": 200,
                "count": 2,
            },
            {
                "order": 3,
                "action_type": "UNAUTHORIZED_ACCESS_ATTEMPT",
                "source": "attack-pod",
                "target": "admin-api",
                "method": "GET",
                "endpoint": "/admin/users",
                "event_type": "restricted_endpoint_access",
                "payload_category": "low_privilege_token",
                "status_code": 403,
                "count": 8,
            },
            {
                "order": 4,
                "action_type": "DATABASE_ACCESS_ATTEMPT",
                "source": "admin-api",
                "target": "postgres-db",
                "method": "CONNECT",
                "endpoint": "tcp/5432",
                "event_type": "database_reachability_attempt",
                "payload_category": "db_probe",
                "status_code": 0,
                "count": 4,
            },
        ],
    },
    {
        "id": "ddos-style",
        "scenario_name": "DDoS-Style Traffic Simulation",
        "description": "Controlled high-volume internal request generation against a lab service.",
        "difficulty": "Intermediate",
        "attack_type": "DDoS-Style Traffic",
        "allowed_template_ids": ["small-company", "e-commerce", "university"],
        "target_services": ["frontend-service", "auth-service", "student-portal"],
        "default_risk": "High",
        "steps": [
            {
                "order": 1,
                "action_type": "CONTROLLED_HIGH_VOLUME_REQUESTS",
                "source": "attack-pod",
                "target": "frontend-service",
                "method": "GET",
                "endpoint": "/home",
                "event_type": "resource_exhaustion_pattern",
                "payload_category": "controlled_high_volume",
                "status_code": 429,
                "count": 72,
            }
        ],
    },
]


DEFENSES = [
    {
        "id": "rate-limit-login",
        "name": "Rate limiting for login endpoints",
        "recommendation_type": "Rate Limiting",
        "action_type": "RATE_LIMIT",
        "attack_types": ["Brute Force", "DDoS-Style Traffic"],
        "description": "Throttle repeated authentication attempts and high-volume requests from the same simulated source.",
        "defense_level": "Application",
        "priority": "High",
    },
    {
        "id": "input-validation",
        "name": "Input validation toggle",
        "recommendation_type": "Input Validation",
        "action_type": "INPUT_VALIDATION",
        "attack_types": ["SQL Injection", "Multi-Stage Attack"],
        "description": "Reject suspicious search input patterns before they reach vulnerable demo handlers.",
        "defense_level": "Application",
        "priority": "High",
    },
    {
        "id": "endpoint-restriction",
        "name": "Admin endpoint access restriction",
        "recommendation_type": "Access Control",
        "action_type": "ENDPOINT_RESTRICTION",
        "attack_types": ["Privilege Escalation", "Lateral Movement", "Multi-Stage Attack"],
        "description": "Restrict sensitive admin routes to trusted services and expected roles only.",
        "defense_level": "Application",
        "priority": "High",
    },
    {
        "id": "network-policy",
        "name": "Kubernetes NetworkPolicy",
        "recommendation_type": "NetworkPolicy",
        "action_type": "NETWORK_POLICY",
        "attack_types": ["Lateral Movement", "Multi-Stage Attack"],
        "description": "Limit service-to-service communication so compromised demo components cannot freely reach admin or database services.",
        "defense_level": "Kubernetes",
        "priority": "Critical",
    },
    {
        "id": "resource-limits",
        "name": "Resource limit adjustment",
        "recommendation_type": "Resource Limits",
        "action_type": "RESOURCE_LIMIT",
        "attack_types": ["DDoS-Style Traffic"],
        "description": "Apply CPU and memory limits so noisy traffic simulations cannot exhaust the local cluster.",
        "defense_level": "Kubernetes",
        "priority": "Medium",
    },
]
